### ISSUE TITLE
Empty icon required when no available slot

### ISSUE THREAD

**Issue by yee2542** [yee2542/CARS-KMUTT-Frontend-Test#12]
![image](https://user-images.githubusercontent.com/18510853/89728908-f7f28780-da5a-11ea-9fbd-9d51ac63b63e.png)

**Comment by octobrekids** [comment]
[Link](https://www.figma.com/file/E0DTvrq6sz7LmIhlRCcvte/CARs?node-id=6383%3A562)
empty icon at staff page

**Comment by yee2542** [comment]
fix on 43895e3b5e26a90df4d82a4f82b205d66b261773
