### ISSUE TITLE
Missing Canvas Icon for Forward Action

### ISSUE THREAD

**Issue by yee2542** [yee2542/CARS-KMUTT-Frontend-Test#13]
Accept Action
![image](https://user-images.githubusercontent.com/18510853/89728953-69cad100-da5b-11ea-854b-17078ad92705.png)
Forward Action
![image](https://user-images.githubusercontent.com/18510853/89728968-88c96300-da5b-11ea-8ec7-0a74d8b10076.png)

**Comment by octobrekids** [comment]
https://www.figma.com/file/E0DTvrq6sz7LmIhlRCcvte/CARs?node-id=6383%3A562
Icon for forwarding action

**Comment by yee2542** [comment]
resolve on b19e93a84d4d5d72c2293a833252af8b8eebff30
