### ISSUE TITLE
Feature Request UI 

### ISSUE THREAD

**Issue by octobrekids** [yee2542/CARS-KMUTT-Frontend-Test#20]
<img width="546" alt="Screen Shot 2563-08-14 at 14 30 20" src="https://user-images.githubusercontent.com/33366852/90225379-75434100-de3b-11ea-904c-f72977cab6e1.png">

**Comment by octobrekids** [comment]
[Link](https://www.figma.com/file/E0DTvrq6sz7LmIhlRCcvte/CARs?node-id=7742%3A3042)

**Comment by yee2542** [comment]
fix on 1b5899b00cdaad220c66a9a64f83a801f7f85182
