### ISSUE TITLE
All area icon required

### ISSUE THREAD

**Issue by octobrekids** [yee2542/CARS-KMUTT-Frontend-Test#30]
<img width="328" alt="Screen Shot 2563-08-25 at 16 41 32" src="https://user-images.githubusercontent.com/33366852/91164704-b966f900-e6f9-11ea-80c3-24b0604734ba.png">

**Comment by octobrekids** [comment]
icon here [Icon](https://www.figma.com/file/E0DTvrq6sz7LmIhlRCcvte/CARs?node-id=7776%3A3058)

**Comment by yee2542** [comment]
@octobrekids can you put it in sidebar.tsx

**Comment by yee2542** [comment]
fixed on #35
