### ISSUE TITLE
Bad selected time for reservation

### ISSUE THREAD

**Issue by octobrekids** [yee2542/CARS-KMUTT-Frontend-Test#31]
<img width="797" alt="Screen Shot 2563-08-25 at 16 34 47" src="https://user-images.githubusercontent.com/33366852/91164808-e4e9e380-e6f9-11ea-965c-fa331dd4e13b.png">

**Comment by yee2542** [comment]
fixing on https://github.com/yee2542/CARS-KMUTT/pull/17

**Comment by yee2542** [comment]
fixed
