### ISSUE TITLE
Timetable slot design required

### ISSUE THREAD

**Issue by octobrekids** [yee2542/CARS-KMUTT-Frontend-Test#32]
![messageImage_1598348540028](https://user-images.githubusercontent.com/33366852/91165033-37c39b00-e6fa-11ea-99a0-192aee9daec4.jpg)

**Comment by octobrekids** [comment]
Design here [Link](https://www.figma.com/file/E0DTvrq6sz7LmIhlRCcvte/CARs?node-id=7781%3A3045)

**Comment by yee2542** [comment]
Layout is integrated wait for backend api

**Comment by yee2542** [comment]
seem it already done
