### ISSUE TITLE
Fix top and bottom bar responsive 

### ISSUE THREAD

**Issue by octobrekids** [yee2542/CARS-KMUTT-Frontend-Test#79]
Need to 
- Separate the hamburger menu and top bar.
- Fix top and bottom bar 
![165024855_530149621717150_5293500697917649173_n](https://user-images.githubusercontent.com/33366852/113297158-7cfd1a80-9324-11eb-9f7d-5c0ddd633652.jpg)
![166113950_448281299781128_1619481054907893411_n](https://user-images.githubusercontent.com/33366852/113297172-8090a180-9324-11eb-99c3-4b761ffda1e5.jpg)
![166992350_930035997742094_4943887589840548922_n](https://user-images.githubusercontent.com/33366852/113297177-81293800-9324-11eb-945c-dd947f085e96.jpg)

**Comment by yeeezsh** [comment]
Seem it already fixed
